#===--app.yaml----------------------------------------------===//
# Part of the Startup-Demos Project, under the MIT License
# See https://github.com/qualcomm/Startup-Demos/blob/main/LICENSE.txt
# for license information.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: MIT License
#===--------------------------------------------------------===//

# app.yaml: The main configuration file for your Arduino App.
# This file describes the application's metadata and properties.

# The user-visible name of the application.
name: TTS Piper

# A brief description of what the application does.
description: ""

# The icon for the application, can be an emoji or a short string.
icon: 😀

# A list of network ports that the application exposes.
# Example: [80, 443]
ports: []

# A list of bricks used by this application.
bricks:
  - arduino:web_ui
