name: "EasyOCR (ONNX)"
description: "A real-time Optical Character Recognition (OCR) application running on Snapdragon X Elite."
category:
  - "CV_VR"
  - "AI_PC"
platforms:
  - "AI PC"
  - "XElite"
tags:
  - "Computer Vision"
  - "Optical Character Recognition"
  - "OCR"
  - "Real-time"
  - "ONNX"
  - "Python"
